name = "AUDL Modded MC"
author = "HyloArch"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6206d0a1512304e8a8dbdafcc89a40a390aecc12791c635ae77eb025576d1126"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
